// Generated by CoffeeScript 1.7.1
var assert, suite, vows, wintersmith;

vows = require('vows');

assert = require('assert');

wintersmith = require('wintersmith');

suite = vows.describe('Plugin');

suite.addBatch({
  'wintersmith environment': {
    topic: function() {
      return wintersmith('./example/config.json');
    },
    'loaded ok': function(env) {
      return assert.instanceOf(env, wintersmith.Environment);
    },
    'contents': {
      topic: function(env) {
        return env.load(this.callback);
      },
      'loaded ok': function(result) {
        return assert.instanceOf(result.contents, wintersmith.ContentTree);
      },
      'has plugin instances': function(result) {
        assert.instanceOf(result.contents['hello.txt'], wintersmith.ContentPlugin);
        assert.isArray(result.contents._.text);
        return assert.lengthOf(result.contents._.text, 2);
      },
      'contains the right text': function(result) {
        var item, _i, _len, _ref, _results;
        _ref = result.contents._.text;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          assert.isString(item.text);
          _results.push(assert.match(item.text, /^Wintersmith is awesome!\n/));
        }
        return _results;
      }
    }
  }
});

suite["export"](module);
